import { createContext, useContext, useState } from "react";
import apiRequest from "../utility/apiRequest";
import { toast } from "react-toastify";

const DataContext = createContext();

export const DataProvider = ({ children }) => {
  // Sub-Admin Data
  const [verifyUsersList, setVerifyUsersList] = useState([
    {
      Name: "1",
      fathersName: "Father 1",
      rollNo: "235UCS001",
      enrollmentNo: "ENR2020001",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1011/300/200",
      isActive: true,
    },
    {
      Name: "2",
      fathersName: "Father 2",
      rollNo: "235UCS002",
      enrollmentNo: "ENR2020002",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1025/300/200",
      isActive: false,
    },
    {
      Name: "3",
      fathersName: "Father 3",
      rollNo: "235UCS003",
      enrollmentNo: "ENR2020003",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1035/300/200",
      isActive: true,
    },
    {
      Name: "4",
      fathersName: "Father 4",
      rollNo: "235UCS004",
      enrollmentNo: "ENR2020004",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1043/300/200",
      isActive: false,
    },
    {
      Name: "5",
      fathersName: "Father 5",
      rollNo: "235UCS005",
      enrollmentNo: "ENR2020005",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1052/300/200",
      isActive: true,
    },
    {
      Name: "6",
      fathersName: "Father 6",
      rollNo: "235UCS006",
      enrollmentNo: "ENR2020006",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1067/300/200",
      isActive: false,
    },
    {
      Name: "7",
      fathersName: "Father 7",
      rollNo: "235UCS007",
      enrollmentNo: "ENR2020007",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1074/300/200",
      isActive: true,
    },
    {
      Name: "8",
      fathersName: "Father 8",
      rollNo: "235UCS008",
      enrollmentNo: "ENR2020008",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1084/300/200",
      isActive: false,
    },
    {
      Name: "9",
      fathersName: "Father 9",
      rollNo: "235UCS009",
      enrollmentNo: "ENR2020009",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/109/300/200",
      isActive: true,
    },
    {
      Name: "10",
      fathersName: "Father 10",
      rollNo: "235UCS010",
      enrollmentNo: "ENR2020010",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/110/300/200",
      isActive: false,
    },
    {
      Name: "11",
      fathersName: "Father 11",
      rollNo: "235UCS011",
      enrollmentNo: "ENR2020011",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/111/300/200",
      isActive: true,
    },
    {
      Name: "12",
      fathersName: "Father 12",
      rollNo: "235UCS012",
      enrollmentNo: "ENR2020012",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/112/300/200",
      isActive: false,
    },
    {
      Name: "13",
      fathersName: "Father 13",
      rollNo: "235UCS013",
      enrollmentNo: "ENR2020013",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/113/300/200",
      isActive: true,
    },
    {
      Name: "14",
      fathersName: "Father 14",
      rollNo: "235UCS014",
      enrollmentNo: "ENR2020014",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/114/300/200",
      isActive: false,
    },
    {
      Name: "15",
      fathersName: "Father 15",
      rollNo: "235UCS015",
      enrollmentNo: "ENR2020015",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/115/300/200",
      isActive: true,
    },
    {
      Name: "16",
      fathersName: "Father 16",
      rollNo: "235UCS016",
      enrollmentNo: "ENR2020016",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/116/300/200",
      isActive: false,
    },
    {
      Name: "17",
      fathersName: "Father 17",
      rollNo: "235UCS017",
      enrollmentNo: "ENR2020017",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/117/300/200",
      isActive: true,
    },
    {
      Name: "18",
      fathersName: "Father 18",
      rollNo: "235UCS018",
      enrollmentNo: "ENR2020018",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/118/300/200",
      isActive: false,
    },
    {
      Name: "19",
      fathersName: "Father 19",
      rollNo: "235UCS019",
      enrollmentNo: "ENR2020019",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/119/300/200",
      isActive: true,
    },
    {
      Name: "20",
      fathersName: "Father 20",
      rollNo: "235UCS020",
      enrollmentNo: "ENR2020020",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/120/300/200",
      isActive: false,
    },
  ]);
  const [activeUsersList, setActiveUsersList] = useState([]);

  // Admin Data
  const [alumniList, setAlumniList] = useState([
    {
      Name: "1",
      fathersName: "Father 1",
      rollNo: "235UCS001",
      enrollmentNo: "ENR2020001",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1011/300/200",
      isActive: true,
    },
    {
      Name: "2",
      fathersName: "Father 2",
      rollNo: "235UCS002",
      enrollmentNo: "ENR2020002",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1025/300/200",
      isActive: false,
    },
    {
      Name: "3",
      fathersName: "Father 3",
      rollNo: "235UCS003",
      enrollmentNo: "ENR2020003",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1035/300/200",
      isActive: true,
    },
    {
      Name: "4",
      fathersName: "Father 4",
      rollNo: "235UCS004",
      enrollmentNo: "ENR2020004",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1043/300/200",
      isActive: false,
    },
    {
      Name: "5",
      fathersName: "Father 5",
      rollNo: "235UCS005",
      enrollmentNo: "ENR2020005",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1052/300/200",
      isActive: true,
    },
    {
      Name: "6",
      fathersName: "Father 6",
      rollNo: "235UCS006",
      enrollmentNo: "ENR2020006",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1067/300/200",
      isActive: false,
    },
    {
      Name: "7",
      fathersName: "Father 7",
      rollNo: "235UCS007",
      enrollmentNo: "ENR2020007",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1074/300/200",
      isActive: true,
    },
    {
      Name: "8",
      fathersName: "Father 8",
      rollNo: "235UCS008",
      enrollmentNo: "ENR2020008",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/1084/300/200",
      isActive: false,
    },
    {
      Name: "9",
      fathersName: "Father 9",
      rollNo: "235UCS009",
      enrollmentNo: "ENR2020009",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/109/300/200",
      isActive: true,
    },
    {
      Name: "10",
      fathersName: "Father 10",
      rollNo: "235UCS010",
      enrollmentNo: "ENR2020010",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/110/300/200",
      isActive: false,
    },
    {
      Name: "11",
      fathersName: "Father 11",
      rollNo: "235UCS011",
      enrollmentNo: "ENR2020011",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/111/300/200",
      isActive: true,
    },
    {
      Name: "12",
      fathersName: "Father 12",
      rollNo: "235UCS012",
      enrollmentNo: "ENR2020012",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/112/300/200",
      isActive: false,
    },
    {
      Name: "13",
      fathersName: "Father 13",
      rollNo: "235UCS013",
      enrollmentNo: "ENR2020013",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/113/300/200",
      isActive: true,
    },
    {
      Name: "14",
      fathersName: "Father 14",
      rollNo: "235UCS014",
      enrollmentNo: "ENR2020014",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/114/300/200",
      isActive: false,
    },
    {
      Name: "15",
      fathersName: "Father 15",
      rollNo: "235UCS015",
      enrollmentNo: "ENR2020015",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/115/300/200",
      isActive: true,
    },
    {
      Name: "16",
      fathersName: "Father 16",
      rollNo: "235UCS016",
      enrollmentNo: "ENR2020016",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/116/300/200",
      isActive: false,
    },
    {
      Name: "17",
      fathersName: "Father 17",
      rollNo: "235UCS017",
      enrollmentNo: "ENR2020017",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/117/300/200",
      isActive: true,
    },
    {
      Name: "18",
      fathersName: "Father 18",
      rollNo: "235UCS018",
      enrollmentNo: "ENR2020018",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/118/300/200",
      isActive: false,
    },
    {
      Name: "19",
      fathersName: "Father 19",
      rollNo: "235UCS019",
      enrollmentNo: "ENR2020019",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/119/300/200",
      isActive: true,
    },
    {
      Name: "20",
      fathersName: "Father 20",
      rollNo: "235UCS020",
      enrollmentNo: "ENR2020020",
      school: "SOICT",
      programme: "CSE",
      country: "India",
      yearOfPassing: "2020",
      degreeURL: "https://picsum.photos/id/120/300/200",
      isActive: false,
    },
  ]);

  const [subAdminList, setSubAdminList] = useState([]);

  return (
    <DataContext.Provider
      value={{
        verifyUsersList,
        setVerifyUsersList,
        activeUsersList,
        setActiveUsersList,
        alumniList,
        setAlumniList,
        subAdminList,
        setSubAdminList,
      }}
    >
      {children}
    </DataContext.Provider>
  );
};

export const useData = () => useContext(DataContext);
